---

dockitems_to_remove:
  - App Store
  - Contacts
  - FaceTime
  - iBooks
  - iTunes
  - Keynote
  - Launchpad
  - Maps
  - Numbers
  - Pages
  - Photos
  - Reminders
  - Safari
  - Siri

dockitems_to_persist:
  Messages:
    path: /Applcations/Messages.app
    pos: 2
  Calendar:
    path: /Applications/Calendar.app
    pos: 3
  Mail:
    path: /Applications/Mail.app
    pos: 4
  Slack:
    path: /Applications/Slack.app
    pos: 5
  Google Chrome:
    path: "/Applications/Google Chrome.app"
    pos: 6
  iTerm:
    path: /Applications/iTerm.app
    pos: 7
  Spotify:
    path: /Applications/Spotify.app
    pos: 8
  Notes:
    path: /Applications/Notes.app
    pos: 9
  Typora:
    path: /Applications/Typora.app
    pos: 10
  System Preferences:
    path: "/Applications/System Preferences.app"
    pos: 11

dock_settings:
  autohide:
    desc: turn on autohide
    type: bool
    value: true
  autohide-delay:
    type: float
    value: 0
    desc: remove autohide delay
  launchanim:
    desc: turn launch animation off
    type: bool
    value: false
  tilesize:
    desc: set tile size
    type: int
    value: 40
  mineffect:
    desc: minimization effect
    type: string
    value: scale
  mru-spaces:
    desc: prevent rearranging of 'spaces' based on use
    type: bool
    value: false
