---

- name: Create ~/.zsh dir
  file:
    path: ~/.zsh
    state: directory

- name: Setup git-completion
  file:
    path: "{{ item.key }}"
    state: link
    src: "{{ item.value.src }}"
  with_dict: git_completion_base

- name: Symlink dotfiles
  file:
    path: "{{ item.key }}"
    state: link
    src: "{{ item.value.src }}"
  with_dict: dotfiles_base
  notify: dotfiles complete
