---

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Create ~/.zsh dir
  file:
    path: ~/.zsh/completion
    state: directory
    recurse: yes

- name: Setup git-completion
  file:
    path: "{{ item.key }}"
    state: link
    src: "{{ item.value.src }}"
    force: yes
  with_dict:
    ~/.zsh/completion/git-completion.bash:
      src: git-completion.bash
    ~/.zsh/completion/_git:
      src: git-completion.zsh

- name: Configure git
  git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  with_dict:
    user.name: Derek Huang
    user.email: derekh919@gmail.com
    pull.rebase: "false"

- name: Copy Operator Mono fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts
    force: no
  with_fileglob: fonts/*

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set permissions for oh-my-zsh
  file:
    path: ~/.oh-my-zsh
    mode: go-w
    recurse: yes
    state: directory
  become: true

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Symlink VSCode settings
  file:
    path: "~/Library/Application Support/Code/User/{{ item }}"
    state: link
    src: "{{ item }}"
    force: yes
  loop:
    - extensions.json
    - settings.json

- name: Create chezmoi config dir
  file:
    path: "{{ HOME }}/.config/chezmoi"
    state: directory

- name: Copy chezmoi config
  copy:
    dest: ~/.config/chezmoi/chezmoi.yml
    src: chezmoi.yml
  ignore_errors: true

- name: Check for chezmoi repo
  stat:
    path: ~/.local/share/chezmoi
  register: chezmoi_dir

- name: Clone dotfiles
  command: chezmoi init https://github.com/dhuang919/dotfiles.git
  when: not chezmoi_dir.stat.exists
