---

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Create ~/.zsh dir
  file:
    path: ~/.zsh
    state: directory

- name: Setup git-completion
  file:
    path: "{{ item.key }}"
    state: link
    src: "{{ item.value.src }}"
  with_dict: "{{ git_completion_base }}"

- name: Clone Powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp
    depth: 1
  become: true

- name: Install Powerline fonts
  shell: /tmp/fonts/install.sh
  become: true

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set permissions for oh-my-zsh
  file:
    path: ~/.oh-my-zsh
    mode: go-w
    recurse: yes
    state: directory
  become: true

- name: Symlink dotfiles
  file:
    path: "{{ item.key }}"
    state: link
    src: "{{ item.value.src }}"
  with_dict: "{{ dotfiles_base }}"
  notify: dotfiles complete
