---

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Create ~/.zsh dir
  file:
    path: ~/.zsh/completion
    state: directory
    recurse: yes

- name: Setup git-completion
  file:
    path: "{{ item.key }}"
    state: link
    src: "{{ item.value.src }}"
  with_dict:
    ~/.zsh/completion/git-completion.bash:
      src: git-completion.bash
    ~/.zsh/completion/_git:
      src: git-completion.zsh

- name: Clone Powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/fonts
    depth: 1
  become: true

- name: Install Powerline fonts
  shell: /tmp/fonts/install.sh
  become: true

- name: Copy Operator Mono fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts
    force: no
  with_fileglob: fonts/*

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set permissions for oh-my-zsh
  file:
    path: ~/.oh-my-zsh
    mode: go-w
    recurse: yes
    state: directory
  become: true

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Symlink VSCode settings
  file:
    path: ~/Library/Application Support/Code/User/settings.json
    state: link
    src: settings.json
