---

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Copy Operator Mono fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts
    force: no
  with_fileglob: fonts/*

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set permissions for oh-my-zsh
  file:
    path: ~/.oh-my-zsh
    mode: go-w
    recurse: yes
    state: directory
  become: true

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Ensure VSCode dir exists
  file:
    path: ~/Library/Application Support/Code/User
    state: directory

- name: Symlink VSCode settings
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/Library/Application Support/Code/User/{{ item }}"
    state: link
  loop:
    - extensions.json
    - settings.json

- name: Create chezmoi config dir
  file:
    path: ~/.config/chezmoi
    state: directory

- name: Copy chezmoi config
  copy:
    dest: ~/.config/chezmoi/chezmoi.yml
    src: chezmoi.yml
  ignore_errors: true

- name: Check for chezmoi repo
  stat:
    path: ~/.local/share/chezmoi
  register: chezmoi_dir

- name: Clone dotfiles
  command: chezmoi init https://github.com/dhuang919/dotfiles.git
  when: not chezmoi_dir.stat.exists
