---

- name: create ~/.zsh dir
  file: path=~/.zsh state=directory

- name: setup zsh git-completion
  file: path={{item.key}} state=link src={{item.value.src}}
  with_dict: git_completion_base

- name: symlink dotfiles
  file: path={{item.key}} state=link src={{item.value.src}}
  with_dict: dotfiles_base
  notify: symlinking dotfiles finished
