---

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Copy Operator Mono fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts
    force: no
  with_fileglob: fonts/*

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set permissions for oh-my-zsh
  file:
    path: ~/.oh-my-zsh
    mode: go-w
    recurse: yes
    state: directory
  become: true

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Ensure Hammerspoon directory exists
  file:
    path: ~/.hammerspoon
    state: directory

- name: Symlink Hammerspoon init
  file:
    src: "{{ role_path }}/files/hammerspoon/init.lua"
    dest: "~/.hammerspoon/init.lua"
    state: link

- name: Check for yadm
  stat:
    path: /usr/bin/yadm
  register: yadm

- name: Install yadm
  shell: curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x /usr/local/bin/yadm
  when: not yadm.stat.exists
  become: true

- name: Check for yadm repo
  stat:
    path: ~/.local/share/yadm/repo.git
  register: yadm_dir

- name: Update dots
  command: yadm pull
  when: yadm_dir.stat.exists

- name: Clone dots
  command: yadm clone https://github.com/dhuang919/dots.git
  when: not yadm_dir.stat.exists
