---

- name: General - scroll bar click behavior
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleScrollerPagingBehavior
    type: bool
    value: 1
    state: present

- name: General - check if bluetooth is in menu bar
  command: defaults read com.apple.systemuiserver menuExtras
  register: result
  changed_when: false

- name: General - set menu bar clock format
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: ss
    state: present

- name: General - turn off font smoothing
  command: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
