---

filesdir: "{{ role_path }}/files"

dotfiles_base:
  ~/Library/Application Support/Code/User/settings.json:
    src: "{{ filesdir }}/settings.json"

git_completion_base:
  ~/.zsh/git-completion.bash:
    src: "{{ filesdir }}/git-completion.bash"
  ~/.zsh/_git:
    src: "{{ filesdir }}/git-completion.zsh"
